# Server Config
server.port=8080

# Database Config
spring.datasource.url=jdbc:mysql://localhost:3306/brocrewz?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Config
brocrewz.app.jwtSecret=BroCrewzStudioSecretKeyForJwtAuthenticationPleaseUseLongerKeyInProduction1234567890
brocrewz.app.jwtExpirationMs=86400000

# SQL Init (Run when DDL is executed)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
